
export const FETCH_NETWORK_DATA_REQUEST = 'FETCH_NETWORK_DATA_REQUEST';
export const FETCH_NETWORK_DATA_SUCCESS = 'FETCH_NETWORK_DATA_SUCCESS';
export const FETCH_NETWORK_DATA_FAILURE = 'FETCH_NETWORK_DATA_FAILURE';
export const SET_NETWORK_FILTER = 'SET_NETWORK_FILTER';
